import type { NextApiRequest, NextApiResponse } from "next";

const API_KEY = (process.env.API_FOOTBALL_KEY || "").trim();
const WC_LEAGUE = 1;
const WC_SEASON = 2026;

const CODE_OVERRIDES: Record<number, string> = {
  1531: "RSA", 17: "KOR", 768: "AUT", 32: "AUS", 1113: "BIH",
  770: "CZE", 497: "IRN", 4301: "IRQ", 107: "COD", 6665: "CPV",
  6667: "CUW", 5529: "CAN",
};

function getCode(teamId: number, apiCode: string | null, name: string): string {
  if (CODE_OVERRIDES[teamId]) return CODE_OVERRIDES[teamId];
  if (apiCode && apiCode.length <= 4) return apiCode.toUpperCase();
  return name.slice(0, 3).toUpperCase();
}

function mapStatus(s: string): string {
  if (["FT","AET"].includes(s)) return "FT";
  if (s === "PEN") return "PEN";
  if (["1H","2H","ET"].includes(s)) return "LIVE";
  if (s === "HT") return "HT";
  if (s === "NS") return "NS";
  return s;
}

// FIFA Annex C: 495 combinations of 8 qualifying 3rd-place groups
// Each 16-char entry: 8-char sorted group key + 8-char slot assignments
// Slots: [1A_opp, 1B_opp, 1D_opp, 1E_opp, 1G_opp, 1I_opp, 1K_opp, 1L_opp]
// Corresponding to matches: M79, M85, M81, M74, M82, M77, M87, M80
const _T = "EFGHIJKLEJIFHGLKDFGHIJKLHGIDJFLKDEGHIJKLEJIDHGLKDEFHIJKLEJIDHFLKDEFGIJKLEGIDJFLKDEFGHJKLEGJDHFLKDEFGHIKLEGIDHFLKDEFGHIJLEGJDHFLIDEFGHIJKEGJDHFIKCFGHIJKLHGICJFLKCEGHIJKLEJICHGLKCEFHIJKLEJICHFLKCEFGIJKLEGICJFLKCEFGHJKLEGJCHFLKCEFGHIKLEGICHFLKCEFGHIJLEGJCHFLICEFGHIJKEGJCHFIKCDGHIJKLHGICJDLKCDFHIJKLCJIDHFLKCDFGIJKLCGIDJFLKCDFGHJKLCGJDHFLKCDFGHIKLCGIDHFLKCDFGHIJLCGJDHFLICDFGHIJKCGJDHFIKCDEHIJKLEJICHDLKCDEGIJKLEGICJDLKCDEGHJKLEGJCHDLKCDEGHIKLEGICHDLKCDEGHIJLEGJCHDLICDEGHIJKEGJCHDIKCDEFIJKLCJEDIFLKCDEFHJKLCJEDHFLKCDEFHIKLCEIDHFLKCDEFHIJLCJEDHFLICDEFHIJKCJEDHFIKCDEFGJKLCGEDJFLKCDEFGIKLCGEDIFLKCDEFGIJLCGEDJFLICDEFGIJKCGEDJFIKCDEFGHKLCGEDHFLKCDEFGHJLCGJDHFLECDEFGHJKCGJDHFEKCDEFGHILCGEDHFLICDEFGHIKCGEDHFIKCDEFGHIJCGJDHFEIBFGHIJKLHJBFIGLKBEGHIJKLEJIBHGLKBEFHIJKLEJBFIHLKBEFGIJKLEJBFIGLKBEFGHJKLEJBFHGLKBEFGHIKLEGBFIHLKBEFGHIJLEJBFHGLIBEFGHIJKEJBFHGIKBDGHIJKLHJBDIGLKBDFHIJKLHJBDIFLKBDFGIJKLIGBDJFLKBDFGHJKLHGBDJFLKBDFGHIKLHGBDIFLKBDFGHIJLHGBDJFLIBDFGHIJKHGBDJFIKBDEHIJKLEJBDIHLKBDEGIJKLEJBDIGLKBDEGHJKLEJBDHGLKBDEGHIKLEGBDIHLKBDEGHIJLEJBDHGLIBDEGHIJKEJBDHGIKBDEFIJKLEJBDIFLKBDEFHJKLEJBDHFLKBDEFHIKLEIBDHFLKBDEFHIJLEJBDHFLIBDEFHIJKEJBDHFIKBDEFGJKLEGBDJFLKBDEFGIKLEGBDIFLKBDEFGIJLEGBDJFLIBDEFGIJKEGBDJFIKBDEFGHKLEGBDHFLKBDEFGHJLHGBDJFLEBDEFGHJKHGBDJFEKBDEFGHILEGBDHFLIBDEFGHIKEGBDHFIKBDEFGHIJHGBDJFEIBCGHIJKLHJBCIGLKBCFHIJKLHJBCIFLKBCFGIJKLIGBCJFLKBCFGHJKLHGBCJFLKBCFGHIKLHGBCIFLKBCFGHIJLHGBCJFLIBCFGHIJKHGBCJFIKBCEHIJKLEJBCIHLKBCEGIJKLEJBCIGLKBCEGHJKLEJBCHGLKBCEGHIKLEGBCIHLKBCEGHIJLEJBCHGLIBCEGHIJKEJBCHGIKBCEFIJKLEJBCIFLKBCEFHJKLEJBCHFLKBCEFHIKLEIBCHFLKBCEFHIJLEJBCHFLIBCEFHIJKEJBCHFIKBCEFGJKLEGBCJFLKBCEFGIKLEGBCIFLKBCEFGIJLEGBCJFLIBCEFGIJKEGBCJFIKBCEFGHKLEGBCHFLKBCEFGHJLHGBCJFLEBCEFGHJKHGBCJFEKBCEFGHILEGBCHFLIBCEFGHIKEGBCHFIKBCEFGHIJHGBCJFEIBCDHIJKLHJBCIDLKBCDGIJKLIGBCJDLKBCDGHJKLHGBCJDLKBCDGHIKLHGBCIDLKBCDGHIJLHGBCJDLIBCDGHIJKHGBCJDIKBCDFIJKLCJBDIFLKBCDFHJKLCJBDHFLKBCDFHIKLCIBDHFLKBCDFHIJLCJBDHFLIBCDFHIJKCJBDHFIKBCDFGJKLCGBDJFLKBCDFGIKLCGBDIFLKBCDFGIJLCGBDJFLIBCDFGIJKCGBDJFIKBCDFGHKLCGBDHFLKBCDFGHJLCGBDHFLJBCDFGHJKHGBCJFDKBCDFGHILCGBDHFLIBCDFGHIKCGBDHFIKBCDFGHIJHGBCJFDIBCDEIJKLEJBCIDLKBCDEHJKLEJBCHDLKBCDEHIKLEIBCHDLKBCDEHIJLEJBCHDLIBCDEHIJKEJBCHDIKBCDEGJKLEGBCJDLKBCDEGIKLEGBCIDLKBCDEGIJLEGBCJDLIBCDEGIJKEGBCJDIKBCDEGHKLEGBCHDLKBCDEGHJLHGBCJDLEBCDEGHJKHGBCJDEKBCDEGHILEGBCHDLIBCDEGHIKEGBCHDIKBCDEGHIJHGBCJDEIBCDEFJKLCJBDEFLKBCDEFIKLCEBDIFLKBCDEFIJLCJBDEFLIBCDEFIJKCJBDEFIKBCDEFHKLCEBDHFLKBCDEFHJLCJBDHFLEBCDEFHJKCJBDHFEKBCDEFHILCEBDHFLIBCDEFHIKCEBDHFIKBCDEFHIJCJBDHFEIBCDEFGKLCGBDEFLKBCDEFGJLCGBDJFLEBCDEFGJKCGBDJFEKBCDEFGILCGBDEFLIBCDEFGIKCGBDEFIKBCDEFGIJCGBDJFEIBCDEFGHLCGBDHFLEBCDEFGHKCGBDHFEKBCDEFGHJHGBCJFDEBCDEFGHICGBDHFEIAFGHIJKLHJIFAGLKAEGHIJKLEJIAHGLKAEFHIJKLEJIFAHLKAEFGIJKLEJIFAGLKAEFGHJKLEGJFAHLKAEFGHIKLEGIFAHLKAEFGHIJLEGJFAHLIAEFGHIJKEGJFAHIKADGHIJKLHJIDAGLKADFHIJKLHJIDAFLKADFGIJKLIGJDAFLKADFGHJKLHGJDAFLKADFGHIKLHGIDAFLKADFGHIJLHGJDAFLIADFGHIJKHGJDAFIKADEHIJKLEJIDAHLKADEGIJKLEJIDAGLKADEGHJKLEGJDAHLKADEGHIKLEGIDAHLKADEGHIJLEGJDAHLIADEGHIJKEGJDAHIKADEFIJKLEJIDAFLKADEFHJKLHJEDAFLKADEFHIKLHEIDAFLKADEFHIJLHJEDAFLIADEFHIJKHJEDAFIKADEFGJKLEGJDAFLKADEFGIKLEGIDAFLKADEFGIJLEGJDAFLIADEFGIJKEGJDAFIKADEFGHKLHGEDAFLKADEFGHJLHGJDAFLEADEFGHJKHGJDAFEKADEFGHILHGEDAFLIADEFGHIKHGEDAFIKADEFGHIJHGJDAFEIACGHIJKLHJICAGLKACFHIJKLHJICAFLKACFGIJKLIGJCAFLKACFGHJKLHGJCAFLKACFGHIKLHGICAFLKACFGHIJLHGJCAFLIACFGHIJKHGJCAFIKACEHIJKLEJICAHLKACEGIJKLEJICAGLKACEGHJKLEGJCAHLKACEGHIKLEGICAHLKACEGHIJLEGJCAHLIACEGHIJKEGJCAHIKACEFIJKLEJICAFLKACEFHJKLHJECAFLKACEFHIKLHEICAFLKACEFHIJLHJECAFLIACEFHIJKHJECAFIKACEFGJKLEGJCAFLKACEFGIKLEGICAFLKACEFGIJLEGJCAFLIACEFGIJKEGJCAFIKACEFGHKLHGECAFLKACEFGHJLHGJCAFLEACEFGHJKHGJCAFEKACEFGHILHGECAFLIACEFGHIKHGECAFIKACEFGHIJHGJCAFEIACDHIJKLHJICADLKACDGIJKLIGJCADLKACDGHJKLHGJCADLKACDGHIKLHGICADLKACDGHIJLHGJCADLIACDGHIJKHGJCADIKACDFIJKLCJIDAFLKACDFHJKLHJFCADLKACDFHIKLHFICADLKACDFHIJLHJFCADLIACDFHIJKHJFCADIKACDFGJKLCGJDAFLKACDFGIKLCGIDAFLKACDFGIJLCGJDAFLIACDFGIJKCGJDAFIKACDFGHKLHGFCADLKACDFGHJLCGJDAFLHACDFGHJKHGJCAFDKACDFGHILHGFCADLIACDFGHIKHGFCADIKACDFGHIJHGJCAFDIACDEIJKLEJICADLKACDEHJKLHJECADLKACDEHIKLHEICADLKACDEHIJLHJECADLIACDEHIJKHJECADIKACDEGJKLEGJCADLKACDEGIKLEGICADLKACDEGIJLEGJCADLIACDEGIJKEGJCADIKACDEGHKLHGECADLKACDEGHJLHGJCADLEACDEGHJKHGJCADEKACDEGHILHGECADLIACDEGHIKHGECADIKACDEGHIJHGJCADEIACDEFJKLCJEDAFLKACDEFIKLCEIDAFLKACDEFIJLCJEDAFLIACDEFIJKCJEDAFIKACDEFHKLHEFCADLKACDEFHJLHJFCADLEACDEFHJKHJECAFDKACDEFHILHEFCADLIACDEFHIKHEFCADIKACDEFHIJHJECAFDIACDEFGKLCGEDAFLKACDEFGJLCGJDAFLEACDEFGJKCGJDAFEKACDEFGILCGEDAFLIACDEFGIKCGEDAFIKACDEFGIJCGJDAFEIACDEFGHLHGFCADLEACDEFGHKHGECAFDKACDEFGHJHGJCAFDEACDEFGHIHGECAFDIABGHIJKLHJBAIGLKABFHIJKLHJBAIFLKABFGIJKLIJBFAGLKABFGHJKLHJBFAGLKABFGHIKLHGBAIFLKABFGHIJLHJBFAGLIABFGHIJKHJBFAGIKABEHIJKLEJBAIHLKABEGIJKLEJBAIGLKABEGHJKLEJBAHGLKABEGHIKLEGBAIHLKABEGHIJLEJBAHGLIABEGHIJKEJBAHGIKABEFIJKLEJBAIFLKABEFHJKLEJBFAHLKABEFHIKLEIBFAHLKABEFHIJLEJBFAHLIABEFHIJKEJBFAHIKABEFGJKLEJBFAGLKABEFGIKLEGBAIFLKABEFGIJLEJBFAGLIABEFGIJKEJBFAGIKABEFGHKLEGBFAHLKABEFGHJLHJBFAGLEABEFGHJKHJBFAGEKABEFGHILEGBFAHLIABEFGHIKEGBFAHIKABEFGHIJHJBFAGEIABDHIJKLIJBDAHLKABDGIJKLIJBDAGLKABDGHJKLHJBDAGLKABDGHIKLIGBDAHLKABDGHIJLHJBDAGLIABDGHIJKHJBDAGIKABDFIJKLIJBDAFLKABDFHJKLHJBDAFLKABDFHIKLHIBDAFLKABDFHIJLHJBDAFLIABDFHIJKHJBDAFIKABDFGJKLFJBDAGLKABDFGIKLIGBDAFLKABDFGIJLFJBDAGLIABDFGIJKFJBDAGIKABDFGHKLHGBDAFLKABDFGHJLHGBDAFLJABDFGHJKHGBDAFJKABDFGHILHGBDAFLIABDFGHIKHGBDAFIKABDFGHIJHGBDAFIJABDEIJKLEJBAIDLKABDEHJKLEJBDAHLKABDEHIKLEIBDAHLKABDEHIJLEJBDAHLIABDEHIJKEJBDAHIKABDEGJKLEJBDAGLKABDEGIKLEGBAIDLKABDEGIJLEJBDAGLIABDEGIJKEJBDAGIKABDEGHKLEGBDAHLKABDEGHJLHJBDAGLEABDEGHJKHJBDAGEKABDEGHILEGBDAHLIABDEGHIKEGBDAHIKABDEGHIJHJBDAGEIABDEFJKLEJBDAFLKABDEFIKLEIBDAFLKABDEFIJLEJBDAFLIABDEFIJKEJBDAFIKABDEFHKLHEBDAFLKABDEFHJLHJBDAFLEABDEFHJKHJBDAFEKABDEFHILHEBDAFLIABDEFHIKHEBDAFIKABDEFHIJHJBDAFEIABDEFGKLEGBDAFLKABDEFGJLEGBDAFLJABDEFGJKEGBDAFJKABDEFGILEGBDAFLIABDEFGIKEGBDAFIKABDEFGIJEGBDAFIJABDEFGHLHGBDAFLEABDEFGHKHGBDAFEKABDEFGHJHGBDAFEJABDEFGHIHGBDAFEIABCHIJKLIJBCAHLKABCGIJKLIJBCAGLKABCGHJKLHJBCAGLKABCGHIKLIGBCAHLKABCGHIJLHJBCAGLIABCGHIJKHJBCAGIKABCFIJKLIJBCAFLKABCFHJKLHJBCAFLKABCFHIKLHIBCAFLKABCFHIJLHJBCAFLIABCFHIJKHJBCAFIKABCFGJKLCJBFAGLKABCFGIKLIGBCAFLKABCFGIJLCJBFAGLIABCFGIJKCJBFAGIKABCFGHKLHGBCAFLKABCFGHJLHGBCAFLJABCFGHJKHGBCAFJKABCFGHILHGBCAFLIABCFGHIKHGBCAFIKABCFGHIJHGBCAFIJABCEIJKLEJBAICLKABCEHJKLEJBCAHLKABCEHIKLEIBCAHLKABCEHIJLEJBCAHLIABCEHIJKEJBCAHIKABCEGJKLEJBCAGLKABCEGIKLEGBAICLKABCEGIJLEJBCAGLIABCEGIJKEJBCAGIKABCEGHKLEGBCAHLKABCEGHJLHJBCAGLEABCEGHJKHJBCAGEKABCEGHILEGBCAHLIABCEGHIKEGBCAHIKABCEGHIJHJBCAGEIABCEFJKLEJBCAFLKABCEFIKLEIBCAFLKABCEFIJLEJBCAFLIABCEFIJKEJBCAFIKABCEFHKLHEBCAFLKABCEFHJLHJBCAFLEABCEFHJKHJBCAFEKABCEFHILHEBCAFLIABCEFHIKHEBCAFIKABCEFHIJHJBCAFEIABCEFGKLEGBCAFLKABCEFGJLEGBCAFLJABCEFGJKEGBCAFJKABCEFGILEGBCAFLIABCEFGIKEGBCAFIKABCEFGIJEGBCAFIJABCEFGHLHGBCAFLEABCEFGHKHGBCAFEKABCEFGHJHGBCAFEJABCEFGHIHGBCAFEIABCDIJKLIJBCADLKABCDHJKLHJBCADLKABCDHIKLHIBCADLKABCDHIJLHJBCADLIABCDHIJKHJBCADIKABCDGJKLCJBDAGLKABCDGIKLIGBCADLKABCDGIJLCJBDAGLIABCDGIJKCJBDAGIKABCDGHKLHGBCADLKABCDGHJLHGBCADLJABCDGHJKHGBCADJKABCDGHILHGBCADLIABCDGHIKHGBCADIKABCDGHIJHGBCADIJABCDFJKLCJBDAFLKABCDFIKLCIBDAFLKABCDFIJLCJBDAFLIABCDFIJKCJBDAFIKABCDFHKLHFBCADLKABCDFHJLCJBDAFLHABCDFHJKHJBCAFDKABCDFHILHFBCADLIABCDFHIKHFBCADIKABCDFHIJHJBCAFDIABCDFGKLCGBDAFLKABCDFGJLCGBDAFLJABCDFGJKCGBDAFJKABCDFGILCGBDAFLIABCDFGIKCGBDAFIKABCDFGIJCGBDAFIJABCDFGHLCGBDAFLHABCDFGHKHGBCAFDKABCDFGHJHGBCAFDJABCDFGHIHGBCAFDIABCDEJKLEJBCADLKABCDEIKLEIBCADLKABCDEIJLEJBCADLIABCDEIJKEJBCADIKABCDEHKLHEBCADLKABCDEHJLHJBCADLEABCDEHJKHJBCADEKABCDEHILHEBCADLIABCDEHIKHEBCADIKABCDEHIJHJBCADEIABCDEGKLEGBCADLKABCDEGJLEGBCADLJABCDEGJKEGBCADJKABCDEGILEGBCADLIABCDEGIKEGBCADIKABCDEGIJEGBCADIJABCDEGHLHGBCADLEABCDEGHKHGBCADEKABCDEGHJHGBCADEJABCDEGHIHGBCADEIABCDEFKLCEBDAFLKABCDEFJLCJBDAFLEABCDEFJKCJBDAFEKABCDEFILCEBDAFLIABCDEFIKCEBDAFIKABCDEFIJCJBDAFEIABCDEFHLHFBCADLEABCDEFHKHEBCAFDKABCDEFHJHJBCAFDEABCDEFHIHEBCAFDIABCDEFGLCGBDAFLEABCDEFGKCGBDAFEKABCDEFGJCGBDAFEJABCDEFGICGBDAFEIABCDEFGHHGBCAFDE";
const THIRD_PLACE_TABLE: Record<string,string> = Object.fromEntries(
  Array.from({length:495},(_,i)=>[_T.slice(i*16,i*16+8),_T.slice(i*16+8,i*16+16)])
);

interface TeamSlot { code: string; name: string }
interface KOMatch { id: string; home: TeamSlot | null; away: TeamSlot | null }

function buildKnockoutSlots(
  groups: Record<string, any[]>,
  qualifying3rds: string[]
): Record<string, KOMatch> {
  const g1 = (g: string): TeamSlot | null =>
    groups[g]?.[0] ? { code: groups[g][0].code, name: groups[g][0].name } : null;
  const g2 = (g: string): TeamSlot | null =>
    groups[g]?.[1] ? { code: groups[g][1].code, name: groups[g][1].name } : null;
  const g3 = (g: string): TeamSlot | null =>
    groups[g]?.[2] ? { code: groups[g][2].code, name: groups[g][2].name } : null;

  const q3key = qualifying3rds.length === 8
    ? qualifying3rds.slice().sort().join("") : null;
  const row = q3key ? (THIRD_PLACE_TABLE[q3key] ?? null) : null;

  const t3 = (idx: number): TeamSlot | null => {
    if (!row) return null;
    const grp = row[idx];
    return qualifying3rds.includes(grp) ? g3(grp) : null;
  };

  return {
    M73: { id:"M73", home:g2("A"), away:g2("B") },
    M74: { id:"M74", home:g1("E"), away:t3(3) },
    M75: { id:"M75", home:g1("F"), away:g2("C") },
    M76: { id:"M76", home:g1("C"), away:g2("F") },
    M77: { id:"M77", home:g1("I"), away:t3(5) },
    M78: { id:"M78", home:g2("E"), away:g2("I") },
    M79: { id:"M79", home:g1("A"), away:t3(0) },
    M80: { id:"M80", home:g1("L"), away:t3(7) },
    M81: { id:"M81", home:g1("D"), away:t3(2) },
    M82: { id:"M82", home:g1("G"), away:t3(4) },
    M83: { id:"M83", home:g2("K"), away:g2("L") },
    M84: { id:"M84", home:g1("H"), away:g2("J") },
    M85: { id:"M85", home:g1("B"), away:t3(1) },
    M86: { id:"M86", home:g1("J"), away:g2("H") },
    M87: { id:"M87", home:g1("K"), away:t3(6) },
    M88: { id:"M88", home:g2("D"), away:g2("G") },
  };
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  res.setHeader("Cache-Control", "s-maxage=20, stale-while-revalidate=40");
  if (!API_KEY) return res.status(500).json({ error: "API_FOOTBALL_KEY not configured" });

  try {
    const hdrs = { "x-apisports-key": API_KEY };
    const [allRes, liveRes, standingsRes] = await Promise.all([
      fetch(`https://v3.football.api-sports.io/fixtures?league=${WC_LEAGUE}&season=${WC_SEASON}`, { headers: hdrs }),
      fetch(`https://v3.football.api-sports.io/fixtures?league=${WC_LEAGUE}&season=${WC_SEASON}&live=all`, { headers: hdrs }),
      fetch(`https://v3.football.api-sports.io/standings?league=${WC_LEAGUE}&season=${WC_SEASON}`, { headers: hdrs }),
    ]);

    const [allData, liveData, standingsData] = await Promise.all([
      allRes.json(), liveRes.json(), standingsRes.json()
    ]);

    const standingsGroups: any[][] = standingsData.response?.[0]?.league?.standings || [];
    const groups: Record<string, any[]> = {};
    for (const group of standingsGroups) {
      if (!group.length) continue;
      const letter = (group[0].group || "").replace(/Group\s*/i, "").trim();
      if (!letter) continue;
      groups[letter] = group.map((t: any) => ({
        rank: t.rank, teamId: t.team.id, name: t.team.name,
        code: getCode(t.team.id, t.team.code || null, t.team.name),
        played: t.all.played, points: t.points, gd: t.goalsDiff, gf: t.all.goals.for,
      }));
    }

    const thirds = (Object.entries(groups) as Array<[string, any[]]>)
      .filter(([, teams]) => teams.length >= 3)
      .map(([letter, teams]) => ({ group: letter, ...teams[2] }))
      .sort((a, b) => b.points - a.points || b.gd - a.gd || b.gf - a.gf);
    const qualifying3rds = thirds.slice(0, 8).map((t) => t.group);
    const knockoutSlots = buildKnockoutSlots(groups, qualifying3rds);

    const allFixtures: any[] = allData.response || [];
    const liveFixtures: any[] = liveData.response || [];
    const liveById: Record<number, any> = {};
    liveFixtures.forEach((f: any) => { liveById[f.fixture.id] = f; });

    const matches = allFixtures.map((f: any) => {
      const src = liveById[f.fixture.id] || f;
      return {
        id: src.fixture.id,
        homeCode: getCode(src.teams.home.id, src.teams.home.code, src.teams.home.name),
        homeName: src.teams.home.name, homeScore: src.goals.home,
        awayCode: getCode(src.teams.away.id, src.teams.away.code, src.teams.away.name),
        awayName: src.teams.away.name, awayScore: src.goals.away,
        status: mapStatus(src.fixture.status.short),
        minute: src.fixture.status.elapsed ?? null,
        round: src.league.round || "", date: src.fixture.date,
        venue: src.fixture.venue?.name || "",
      };
    });

    const liveMatches = liveFixtures.map((f: any) => ({
      id: f.fixture.id,
      status: f.fixture.status.short === "HT" ? "HT" : "LIVE",
      minute: f.fixture.status.elapsed ?? 0,
      hTeam: f.teams.home.name,
      hAbbr: getCode(f.teams.home.id, f.teams.home.code, f.teams.home.name),
      aTeam: f.teams.away.name,
      aAbbr: getCode(f.teams.away.id, f.teams.away.code, f.teams.away.name),
      hScore: f.goals.home ?? 0, aScore: f.goals.away ?? 0,
      venue: f.fixture.venue?.name || "", scorers: [],
    }));

    const knockoutPaths: Record<string,{id:string,home:string,away:string}> = {
      // Round of 32 - predetermined FIFA structure labels
      M73:{id:"M73",home:"2nd-A",away:"2nd-B"},
      M74:{id:"M74",home:"1st-E",away:"3rd-EFGI"},
      M75:{id:"M75",home:"1st-F",away:"2nd-C"},
      M76:{id:"M76",home:"1st-C",away:"2nd-F"},
      M77:{id:"M77",home:"1st-I",away:"3rd-BFIK"},
      M78:{id:"M78",home:"2nd-E",away:"2nd-I"},
      M79:{id:"M79",home:"1st-A",away:"3rd-ABCD"},
      M80:{id:"M80",home:"1st-L",away:"3rd-JKLA"},
      M81:{id:"M81",home:"1st-D",away:"3rd-DEFG"},
      M82:{id:"M82",home:"1st-G",away:"3rd-GHIJ"},
      M83:{id:"M83",home:"2nd-K",away:"2nd-L"},
      M84:{id:"M84",home:"1st-H",away:"2nd-J"},
      M85:{id:"M85",home:"1st-B",away:"3rd-BCEH"},
      M86:{id:"M86",home:"1st-J",away:"2nd-H"},
      M87:{id:"M87",home:"1st-K",away:"3rd-IJKL"},
      M88:{id:"M88",home:"2nd-D",away:"2nd-G"},
      // Round of 16
      M89:{id:"M89",home:"W-M73",away:"W-M74"}, M90:{id:"M90",home:"W-M75",away:"W-M76"},
      M91:{id:"M91",home:"W-M77",away:"W-M78"}, M92:{id:"M92",home:"W-M79",away:"W-M80"},
      M93:{id:"M93",home:"W-M81",away:"W-M82"}, M94:{id:"M94",home:"W-M83",away:"W-M84"},
      M95:{id:"M95",home:"W-M85",away:"W-M86"}, M96:{id:"M96",home:"W-M87",away:"W-M88"},
      // Quarter Finals
      M97:{id:"M97",home:"W-M89",away:"W-M90"}, M98:{id:"M98",home:"W-M91",away:"W-M92"},
      M99:{id:"M99",home:"W-M93",away:"W-M94"}, M100:{id:"M100",home:"W-M95",away:"W-M96"},
      // Semi Finals
      M101:{id:"M101",home:"W-M97",away:"W-M98"}, M102:{id:"M102",home:"W-M99",away:"W-M100"},
    };
    return res.status(200).json({
      updatedAt: new Date().toISOString(),
      matches, liveMatches, groups, qualifying3rds, knockoutSlots, knockoutPaths,
    });
  } catch (err) {
    return res.status(500).json({ error: "Failed to fetch bracket data", message: String(err) });
  }
}